### ISSUE TITLE
Dockerfile for hamat/web-altas-data-conversion

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/vitessce-pipeline#11]
We should include Dockerfile for hamat/web-altas-data-conversion

**Comment by BioinfoTongLI** [comment]
tho, there was a lot of deps that was added in [this commit](docker/requirements.txt). Are they still needed?

**Comment by davehorsfall** [comment]
Closed with ca7a2a16512ab3b47bf06218d98a5bc842588d4d
