### ISSUE TITLE
reading spot ids problem

### ISSUE THREAD

**Issue by iolosquires** [haniffalab/vitessce-pipeline#40]
When I tried to put visium spatial data into the pipeline, I get an error where it can't read the spatial information correctly. The error I get is: 

"ValueError: invalid literal for int() with base 10: 'spaceranger130_count_36654_WSSS_F_IMMsp9838712_GRCh38-2020-A_AAACAAGTATCTCCCA-1'"

**Comment by BioinfoTongLI** [comment]
@davehorsfall sounds good! - @iolosquires feel free to ask anything here.

**Comment by davehorsfall** [comment]
Resolved
