### ISSUE TITLE
Unable to find image 'hamat/webatlas-router:0.0.1' locally

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/vitessce-pipeline#45]
```
Command error:
  Unable to find image 'hamat/webatlas-router:0.0.1' locally
  docker: Error response from daemon: manifest for hamat/webatlas-router:0.0.1 not found: manifest unknown: manifest unknown.
  See 'docker run --help'.
```

**Comment by davehorsfall** [comment]
Pipeline trying to pull a tagged Docker image, that doesn't exist.
https://hub.docker.com/r/hamat/webatlas-router

**Comment by BioinfoTongLI** [comment]
Sorry somehow I wasn't notified here. I assume we will be switching to a unified dockerhub repo? The haniffa lab one maybe?
I would deprecate all docker images pointing to  `hamat` account.
